version: '3.8'

services:
  db-dev:
    image: postgres:15
    container_name: db-dev
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devbookmark_dev
    ports:
      - "5432:5432"
    volumes:
      - dev-db:/var/lib/postgresql/data

  db-test:
    image: postgres:15
    container_name: db-test
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devbookmark_test
    ports:
      - "5433:5432"
    volumes:
      - test-db:/var/lib/postgresql/data

  db-prod:
    image: postgres:15
    container_name: db-prod
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devbookmark_prod
    ports:
      - "5434:5432"
    volumes:
      - prod-db:/var/lib/postgresql/data

volumes:
  dev-db:
  test-db:
  prod-db:
